export type Country =
  | "Aruba"
  | "Afghánistán"
  | "Angola"
  | "Anguilla"
  | "Ålandy"
  | "Albánie"
  | "Andorra"
  | "Spojené arabské emiráty"
  | "Argentina"
  | "Arménie"
  | "Americká Samoa"
  | "Antarktida"
  | "Francouzská jižní a antarktická území"
  | "Antigua a Barbuda"
  | "Austrálie"
  | "Rakousko"
  | "Ázerbájdžán"
  | "Burundi"
  | "Belgie"
  | "Benin"
  | "Burkina Faso"
  | "Bangladéš"
  | "Bulharsko"
  | "Bahrajn"
  | "Bahamy"
  | "Bosna a Hercegovina"
  | "Svatý Bartoloměj"
  | "Svatá Helena, Ascension a Tristan da Cunha"
  | "Bělorusko"
  | "Belize"
  | "Bermudy"
  | "Bolívie"
  | "Karibské Nizozemsko"
  | "Brazílie"
  | "Barbados"
  | "Brunej"
  | "Bhútán"
  | "Bouvetův ostrov"
  | "Botswana"
  | "Středoafrická republika"
  | "Kanada"
  | "Kokosové ostrovy"
  | "Švýcarsko"
  | "Chile"
  | "Čína"
  | "Pobřeží slonoviny"
  | "Kamerun"
  | "DR Kongo"
  | "Kongo"
  | "Cookovy ostrovy"
  | "Kolumbie"
  | "Komory"
  | "Kapverdy"
  | "Kostarika"
  | "Kuba"
  | "Curaçao"
  | "Vánoční ostrov"
  | "Kajmanské ostrovy"
  | "Kypr"
  | "Česko"
  | "Německo"
  | "Džibutsko"
  | "Dominika"
  | "Dánsko"
  | "Dominikánská republika"
  | "Alžírsko"
  | "Ekvádor"
  | "Egypt"
  | "Eritrea"
  | "Západní Sahara"
  | "Španělsko"
  | "Estonsko"
  | "Etiopie"
  | "Finsko"
  | "Fidži"
  | "Falklandy"
  | "Francie"
  | "Faerské ostrovy"
  | "Mikronésie"
  | "Gabon"
  | "Spojené království"
  | "Gruzie"
  | "Guernsey"
  | "Ghana"
  | "Gibraltar"
  | "Guinea"
  | "Guadeloupe"
  | "Gambie"
  | "Guinea-Bissau"
  | "Rovníková Guinea"
  | "Řecko"
  | "Grenada"
  | "Grónsko"
  | "Guatemala"
  | "Francouzská Guyana"
  | "Guam"
  | "Guyana"
  | "Hongkong"
  | "Heardův ostrov a McDonaldovy ostrovy"
  | "Honduras"
  | "Chorvatsko"
  | "Haiti"
  | "Maďarsko"
  | "Indonésie"
  | "Ostrov Man"
  | "Indie"
  | "Britské indickooceánské území"
  | "Irsko"
  | "Írán"
  | "Irák"
  | "Island"
  | "Izrael"
  | "Itálie"
  | "Jamajka"
  | "Jersey"
  | "Jordánsko"
  | "Japonsko"
  | "Kazachstán"
  | "Keňa"
  | "Kyrgyzstán"
  | "Kambodža"
  | "Kiribati"
  | "Svatý Kryštof a Nevis"
  | "Jižní Korea"
  | "Kosovo"
  | "Kuvajt"
  | "Laos"
  | "Libanon"
  | "Libérie"
  | "Libye"
  | "Svatá Lucie"
  | "Lichtenštejnsko"
  | "Srí Lanka"
  | "Lesotho"
  | "Litva"
  | "Lucembursko"
  | "Lotyšsko"
  | "Macao"
  | "Svatý Martin (Francie)"
  | "Maroko"
  | "Monako"
  | "Moldavsko"
  | "Madagaskar"
  | "Maledivy"
  | "Mexiko"
  | "Marshallovy ostrovy"
  | "Severní Makedonie"
  | "Mali"
  | "Malta"
  | "Myanmar"
  | "Černá Hora"
  | "Mongolsko"
  | "Severní Mariany"
  | "Mosambik"
  | "Mauritánie"
  | "Montserrat"
  | "Martinik"
  | "Mauricius"
  | "Malawi"
  | "Malajsie"
  | "Mayotte"
  | "Namibie"
  | "Nová Kaledonie"
  | "Niger"
  | "Norfolk"
  | "Nigérie"
  | "Nikaragua"
  | "Niue"
  | "Nizozemsko"
  | "Norsko"
  | "Nepál"
  | "Nauru"
  | "Nový Zéland"
  | "Omán"
  | "Pákistán"
  | "Panama"
  | "Pitcairnovy ostrovy"
  | "Peru"
  | "Filipíny"
  | "Palau"
  | "Papua-Nová Guinea"
  | "Polsko"
  | "Portoriko"
  | "Severní Korea"
  | "Portugalsko"
  | "Paraguay"
  | "Palestina"
  | "Francouzská Polynésie"
  | "Katar"
  | "Réunion"
  | "Rumunsko"
  | "Rusko"
  | "Rwanda"
  | "Saúdská Arábie"
  | "Súdán"
  | "Senegal"
  | "Singapur"
  | "Jižní Georgie a Jižní Sandwichovy ostrovy"
  | "Špicberky a Jan Mayen"
  | "Šalamounovy ostrovy"
  | "Sierra Leone"
  | "Salvador"
  | "San Marino"
  | "Somálsko"
  | "Saint-Pierre a Miquelon"
  | "Srbsko"
  | "Jižní Súdán"
  | "Svatý Tomáš a Princův ostrov"
  | "Surinam"
  | "Slovensko"
  | "Slovinsko"
  | "Švédsko"
  | "Svazijsko"
  | "Svatý Martin (Nizozemsko)"
  | "Seychely"
  | "Sýrie"
  | "Turks a Caicos"
  | "Čad"
  | "Togo"
  | "Thajsko"
  | "Tádžikistán"
  | "Tokelau"
  | "Turkmenistán"
  | "Východní Timor"
  | "Tonga"
  | "Trinidad a Tobago"
  | "Tunisko"
  | "Turecko"
  | "Tuvalu"
  | "Tchaj-wan"
  | "Tanzanie"
  | "Uganda"
  | "Ukrajina"
  | "Menší odlehlé ostrovy USA"
  | "Uruguay"
  | "Spojené státy"
  | "Uzbekistán"
  | "Vatikán"
  | "Svatý Vincenc a Grenadiny"
  | "Venezuela"
  | "Britské Panenské ostrovy"
  | "Americké Panenské ostrovy"
  | "Vietnam"
  | "Vanuatu"
  | "Wallis a Futuna"
  | "Samoa"
  | "Jemen"
  | "Jihoafrická republika"
  | "Zambie"
  | "Zimbabwe"
