import { library } from "@fortawesome/fontawesome-svg-core"
import { faCircle, faCircleDot, faSquare } from "@fortawesome/pro-regular-svg-icons"
import {
  faArrowRight,
  faBookSection,
  faCalculatorSimple,
  faFilePdf,
  faHandshakeSimple,
  faLock,
  faHeartPulse,
  faMegaphone,
  faStethoscope,
  faToggleOff,
  faToggleOn,
  faPencil,
  faPhone,
  faCheck,
  faClose,
  faPlus,
  faEllipsisVertical,
  faListOl,
  faAddressCard,
  faPowerOff,
  faHouseUser,
  faCar,
  faPersonWalkingWithCane,
  faCreditCard,
  faUserTieHair,
  faChartCandlestick,
} from "@fortawesome/pro-light-svg-icons"
import { faFacebook, faInstagram, faLinkedin } from "@fortawesome/free-brands-svg-icons"
import {
  faAngleLeft,
  faCaretDown,
  faTriangleExclamation,
  faChevronLeft,
  faChevronRight,
  faPaperclip,
  faTimesCircle,
} from "@fortawesome/pro-solid-svg-icons"

library.add(
  faAngleLeft,
  faArrowRight,
  faBookSection,
  faCalculatorSimple,
  faCaretDown,
  faClose,
  faEllipsisVertical,
  faFacebook,
  faFilePdf,
  faHandshakeSimple,
  faHeartPulse,
  faInstagram,
  faLinkedin,
  faCheck,
  faLock,
  faMegaphone,
  faPencil,
  faPhone,
  faPlus,
  faPowerOff,
  faStethoscope,
  faToggleOff,
  faToggleOn,
  faTriangleExclamation,
  faListOl,
  faCircleDot,
  faCircle,
  faSquare,
  faAddressCard,
  faChevronLeft,
  faChevronRight,
  faHouseUser,
  faCar,
  faPersonWalkingWithCane,
  faCreditCard,
  faUserTieHair,
  faChartCandlestick,
  faPaperclip,
  faTimesCircle,
  faPaperclip,
  faTimesCircle,
)
